# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\nclassifier\"\x1e\n\x0ePredictRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\xa1\x01\n\x0fPredictResponse\x12\x18\n\x10\x63omputer_science\x18\x01 \x01(\x08\x12\x0f\n\x07physics\x18\x02 \x01(\x08\x12\x13\n\x0bmathematics\x18\x03 \x01(\x08\x12\x12\n\nstatistics\x18\x04 \x01(\x08\x12\x1c\n\x14quantitative_biology\x18\x05 \x01(\x08\x12\x1c\n\x14quantitative_finance\x18\x06 \x01(\x08\x32^\n\x11\x43lassifierService\x12I\n\x0c\x43lassifyText\x12\x1a.classifier.PredictRequest\x1a\x1b.classifier.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=29
  _globals['_PREDICTREQUEST']._serialized_end=59
  _globals['_PREDICTRESPONSE']._serialized_start=62
  _globals['_PREDICTRESPONSE']._serialized_end=223
  _globals['_CLASSIFIERSERVICE']._serialized_start=225
  _globals['_CLASSIFIERSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
